# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZNWkSRc95TJVLpk9Lpji3to6W0ZHQBJ
"""

# ============================================================
# Project    : Python for Electrical Engineering
# Topic      : Conditional Statements
# Example 01 : Motor Overload Protection
# Student    : Ridoy Chandra Shill
# University : Eastern University
# Department : Electrical and Electronic Engineering (EEE)
# ============================================================

print("========== Motor Overload Protection ==========")

Assistent_engineer = "Engr. Ridoy Chandra Shill"
motor_name = "Conveyor Belt Drive Motor"

rated_current = float(input("Enter the rated current (A): "))
measured_current = float(input("Enter the measured current (A): "))

print("\nInspection Report")
print("-" * 45)

print(f"Assistent Engineer : {Assistent_engineer}")
print(f"Motor Name          : {motor_name}")
print(f"Rated Current       : {rated_current:.2f} A")
print(f"Measured Current    : {measured_current:.2f} A")

print("\nInspection Result")
print("-" * 45)

if measured_current <= rated_current:
    print("Status         : Normal Operation")
    print("Condition      : Motor is operating within the rated current.")
    print(f"Verified By    : {Assistent_engineer}")
    print("Recommendation : Continue normal operation.")

elif measured_current <= rated_current * 1.10:
    print("Status         : Light Overload")
    print("Condition      : Current is slightly above the rated value.")
    print(f"Notify         : {Assistent_engineer}")
    print("Recommendation : Monitor the motor and reduce the mechanical load.")

elif measured_current <= rated_current * 1.20:
    print("Status         : High Overload")
    print("Condition      : Motor may overheat if operated continuously.")
    print(f"Notify         : {Assistent_engineer}")
    print("Recommendation : Stop the motor and inspect the drive system.")

else:
    print("Status        : Critical Overload")
    print("Condition      : Current exceeds 120% of the rated value.")
    print(f"Notify         : {Assistent_engineer} immediately.")
    print("Recommendation : Shut down the motor immediately and inspect the protection system.")

print("\nInspection completed.")

# ============================================================
# Project    : Python for Electrical Engineering
# Topic      : Conditional Statements
# Example 02 : Supply Voltage Monitoring
# Engineer    : Ridoy Chandra Shill
# ============================================================

print("========== Supply Voltage Monitoring ==========")

Assistent_engineer = "Engr. Ridoy Chandra Shill"

nominal_voltage = 230      # V (Bangladesh Standard)
measured_voltage = float(input("Enter the measured supply voltage (V): "))

print("\nVoltage Inspection Report")
print("-" * 45)

print(f"Assistent Engineer : {Assistent_engineer}")
print(f"Nominal Voltage     : {nominal_voltage} V")
print(f"Measured Voltage    : {measured_voltage:.1f} V")

print("\nInspection Result")
print("-" * 45)

if measured_voltage < 210:
    print("Status         : Low Voltage")
    print("Risk           : Equipment may not operate properly.")
    print(f"Notify         : {Assistent_engineer}")
    print("Recommendation : Inspect the power supply and feeder line.")

elif measured_voltage <= 240:
    print("Status         : Normal Voltage")
    print("Condition      : Supply voltage is within the acceptable range.")
    print(f"Verified By    : {Assistent_engineer}")
    print("Recommendation : Continue normal operation.")

else:
    print("Status         : High Voltage")
    print("Risk           : Equipment insulation may be stressed.")
    print(f"Notify         : {Assistent_engineer}")
    print("Recommendation : Check the transformer tap setting and supply system.")

print("\nVoltage inspection completed successfully.")
