# -*- coding: utf-8 -*-
"""Data_Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiP9hhLdzE6B1zH8naZCGU1by_Mcfy7w
"""

# ============================================================
# Practice Programme 01 : Python for Electrical Engineering
# Topic      : Lists
# Example 01 : Solar Energy Data Logger
# ============================================================

solar_energy = []

print("Solar Energy Data Logger")
print("-" * 40)

# Store solar energy data for 7 days
for day in range(1, 8):

    energy = float(input(f"Day {day} Energy (kWh): "))
    solar_energy.append(energy)

print("\nDaily Energy Generation")

for day, energy in enumerate(solar_energy, start=1):
    print(f"Day {day} : {energy} kWh")

print("\nWeekly Summary")

print(f"Total Energy   : {sum(solar_energy):.2f} kWh")
print(f"Average Energy : {sum(solar_energy)/len(solar_energy):.2f} kWh")
print(f"Highest Energy : {max(solar_energy):.2f} kWh")
print(f"Lowest Energy  : {min(solar_energy):.2f} kWh")

# ============================================================
# Practice Programe    : Python for Electrical Engineering
# Topic      : Tuples
# Example 02 : Transformer Nameplate Data
# ============================================================

print("========== Transformer Nameplate ==========\n")

transformer = (
    "Siemens",   # Brand
    500,         # Rating (kVA)
    11,          # Primary Voltage (kV)
    415,         # Secondary Voltage (V)
    50,          # Frequency (Hz)
    "ONAN"       # Cooling Type
)

print(f"Brand              : {transformer[0]}")
print(f"Rating             : {transformer[1]} kVA")
print(f"Primary Voltage    : {transformer[2]} kV")
print(f"Secondary Voltage  : {transformer[3]} V")
print(f"Frequency          : {transformer[4]} Hz")
print(f"Cooling Type       : {transformer[5]}")

# ============================================================
# Practice Programe    : Python for Electrical Engineering
# Topic      : Sets
# Example 01 : PLC Digital Input Status
# ============================================================

print("========== PLC Digital Input Status ==========\n")

active_inputs = set()

number_of_inputs = int(input("How many active PLC inputs? "))

print()

for i in range(number_of_inputs):

    plc_input = input(f"Enter Active Input {i + 1}: ").upper()

    active_inputs.add(plc_input)

print("\n========== Active PLC Inputs ==========\n")

for input_signal in sorted(active_inputs):

    if input_signal == "X0":
        print("X0 → Start Push Button")

    elif input_signal == "X1":
        print("X1 → Stop Push Button")

    elif input_signal == "X2":
        print("X2 → Emergency Stop")

    elif input_signal == "X3":
        print("X3 → Photoelectric Sensor")

    elif input_signal == "X4":
        print("X4 → Limit Switch")

    elif input_signal == "X5":
        print("X5 → Proximity Sensor")

    else:
        print(f"{input_signal} → Unknown Input")

print(f"\nTotal Active Inputs : {len(active_inputs)}")

# ============================================================
# Programme example    : Python for Electrical Engineering
# Topic      : Dictionaries
# Example 04 : Electrical Cable Size Reference
# ============================================================

print("========== Electrical Cable Size Reference ==========\n")

cable = {
    "1.5": "14 A",
    "2.5": "20 A",
    "4": "26 A",
    "6": "34 A",
    "10": "46 A",
    "16": "61 A"
}

print("Available Cable Sizes")

for size in cable:
    print(size, "mm²")

print()

search = input("Enter Cable Size (mm²): ")

print()

if search in cable:

    print("========== Cable Information ==========\n")
    print("Cable Size    :", search, "mm²")
    print("Current Rating:", cable[search])

else:

    print("Cable Size Not Found.")