# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXjP2A5UOi_uDD37WalJpoWep5-zpwH4
"""

# ============================================================
# Practice Program 01: Python for Electrical Engineering
# Topic      : Functions
# Example 01 : Solar Power Estimator
# Mathematical Background

# Step 1:
# Calculate the total installed solar capacity.
# Total Capacity (W) = Number of Panels × Power per Panel (W)

# Step 2:
# Estimate the daily energy generation.
# Daily Energy (kWh) = (Total Capacity (W) × Sunlight Hours) / 1000
# ============================================================


# Display solar panel information
def show_panel_information():

    print("\n========== Solar Panel Information ==========")
    print("Number of Panels :", number_of_panels)
    print("Power per Panel  :", panel_power, "W")
    print("Sunlight Hours   :", sunlight_hours, "Hours")


# Calculate total solar capacity
def calculate_total_capacity():

    total_capacity = number_of_panels * panel_power
    return total_capacity


# Calculate daily energy generation
def calculate_daily_energy(total_capacity):

    daily_energy = (total_capacity * sunlight_hours) / 1000
    return daily_energy


# Display final report
def show_report(total_capacity, daily_energy):

    print("\n========== Solar Energy Report ==========")
    print(f"Total Capacity : {total_capacity} W")
    print(f"Daily Energy   : {daily_energy:.2f} kWh")


# ---------------- Main Program ----------------

number_of_panels = int(input("Enter number of solar panels : "))
panel_power = float(input("Enter power of one panel (W) : "))
sunlight_hours = float(input("Enter average sunlight hours : "))

show_panel_information()

total_capacity = calculate_total_capacity()
daily_energy = calculate_daily_energy(total_capacity)

show_report(total_capacity, daily_energy)

# ============================================================
# Practice Program 02: Python for Electrical Engineering
# Topic      : Functions
# Example 02 : Solar Charge Time Estimator
# Mathematical Background
# Step 1:
# Calculate the stored energy of the battery.
# Battery Energy (Wh) = Battery Voltage (V) × Battery Capacity (Ah)

# Step 2:
# Estimate the battery charging time using the available solar power.
# Charging Time (Hours) = Battery Energy (Wh) / Solar Charging Power (W)
# ============================================================


# Calculate battery energy
def battery_energy(voltage, capacity):

    energy = voltage * capacity

    return energy


# Estimate charging time
def charging_time(energy, solar_power):

    time = energy / solar_power

    return time


print(" ======= Solar Charge Time Estimator ====== ")

battery_voltage = float(input("Enter battery voltage (V): "))
battery_capacity = float(input("Enter battery capacity (Ah): "))
solar_power = float(input("Enter solar charging power (W): "))

energy = battery_energy(battery_voltage, battery_capacity)

time = charging_time(energy, solar_power)

print("\n ======= Charging Report ========= ")
print(f"Battery Energy  : {energy:.2f} Wh")
print(f"Solar Charging Power  : {solar_power:.2f} W")
print(f"Estimated Charge Time  : {time:.2f} Hours")

if time <= 4:
    print("Charging Status        : Fast Charging")

elif time <= 8:
    print("Charging Status        : Normal Charging")

else:
    print("Charging Status        : Slow Charging")