# -*- coding: utf-8 -*-
"""OOP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRg2v4ljHpfw-9LNUQIp_mbVuOy0l6x_
"""

# ============================================================
# Practice Program    : Python for Electrical Engineering
# Topic      : Object-Oriented Programming (OOP)
# Example 01 : Industrial Temperature Monitoring System
# ============================================================

class TemperatureSensor:

    def __init__(self, sensor_name, temperature):
        self.sensor_name =   sensor_name
        self.temperature = temperature

    def check_temperature(self):

        if self.temperature > 80:
            return "High Temperature"

        elif self.temperature < 20:
            return "Low Temperature"

        else:
            return "Normal Temperature"

    def show_status(self):

        print("Sensor Name :", self.sensor_name)
        print("Temperature  :", self.temperature, "°C")
        print("Status       :", self.check_temperature())


print("========== Industrial Temperature Monitoring ==========\n")

temperature = float(input("Enter current temperature (°C): "))

sensor = TemperatureSensor("RTD-01", temperature)

print("\n========== Sensor Status ==========\n")

sensor.show_status()

# ============================================================
# Practice Program    : Python for Electrical Engineering
# Topic      : Object-Oriented Programming (OOP)
# Example 02 : Industrial Pump Control System
# ============================================================

class WaterPump:

    def __init__(self, pump_name, rated_power, current, water_level):
        self.pump_name = pump_name
        self.rated_power = rated_power
        self.current = current
        self.water_level = water_level
        self.pump_status = "OFF"

    def check_water_level(self):

        if self.water_level < 25:
            self.pump_status = "ON"
            return "Tank level is low."

        elif self.water_level > 70:
            self.pump_status = "OFF"
            return "Tank level is sufficient."

        else:
            self.pump_status = "ON"
            return "Water level is within operating range."

    def show_status(self):

        message = self.check_water_level()

        print("\n========== Pump Status ==========")
        print("Pump Name   :", self.pump_name)
        print("Rated Power :", self.rated_power, "kW")
        print("Current     :", self.current, "A")
        print("Water Level :", self.water_level, "%")
        print("Pump Status :", self.pump_status)
        print("Action      :", message)


print("========== Industrial Pump Control System ==========\n")

pump_name = input("Enter Pump Name: ")
rated_power = float(input("Enter Rated Power (kW): "))
current = float(input("Enter Current (A): "))
water_level = float(input("Enter Water Level (%): "))

pump = WaterPump(
    pump_name,
    rated_power,
    current,
    water_level
)

pump.show_status()