# -*- coding: utf-8 -*-
"""python_loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZNWkSRc95TJVLpk9Lpji3to6W0ZHQBJ
"""

# ============================================================
# Project    : Python for Electrical Engineering
# Topic      : Loops
# Example 01 : Conveyor Fruit Sorting System
# ============================================================

print("========== Conveyor Fruit Sorting System ==========")

# Fruits detected on the conveyor
detected_items = [
    "Orange",
    "Mango",
    "Apple",
    "Banana"
]

orange_count = 0
mango_count = 0
apple_count = 0
banana_count = 0

box_number = 1

print("\nConveyor Status : RUNNING")
print("-" * 55)

for item in detected_items:

    print(f"\nBox {box_number}")
    print(f"Detected Item : {item}")

    if item == "Orange":

        print("\nSensor Status")
        print("Sensor-1 :   ON")
        print("Sensor-2 : OFF")
        print("Sensor-3 : OFF")
        print("Sensor-4 : OFF")

        print("\nPLC Command : Move box to Lane-A")
        print("Sorting Status  : Completed")

        orange_count += 1

    elif item == "Mango":

        print("\nSensor Status")
        print("Sensor-1 : OFF")
        print("Sensor-2 :   ON")
        print("Sensor-3 : OFF")
        print("Sensor-4 : OFF")

        print("\nPLC Command : Move box to Lane-B")
        print("Sorting Status : Completed")

        mango_count += 1

    elif item == "Apple":

        print("\nSensor Status")
        print("Sensor-1 : OFF")
        print("Sensor-2 : OFF")
        print("Sensor-3 :   ON")
        print("Sensor-4 : OFF")

        print("\nPLC Command : Move box to Lane-C")
        print("Sorting Status : Completed")

        apple_count += 1

    else:

        print("\nSensor Status")
        print("Sensor-1 : OFF")
        print("Sensor-2 : OFF")
        print("Sensor-3 : OFF")
        print("Sensor-4 :   ON")

        print("\nPLC Command : Move box to Lane-D")
        print("Sorting Status : Completed")

        banana_count += 1

    box_number += 1

print("Production Summary")
print("=" * 45)

print(f"Total Boxes Sorted : {len(detected_items)}")
print(f"Orange Boxes  : {orange_count}")
print(f"Mango Boxes    : {mango_count}")
print(f"Apple Boxes       : {apple_count}")
print(f"Banana Boxes   : {banana_count}")

print("\nSystem Status")
print("Conveyor : STOPPED")
print("PLC       : READY FOR NEXT BATCH")
print("=" * 55)

# ============================================================
# Project    : Python for Electrical Engineering
# Topic      : While Loop
# Example 02 : Traffic Signal Controllering
# ============================================================

print("========== Traffic Signal Controllering ==========")

cycle = 1

while True:

    print("\n" + "=" * 45)
    print(f"Traffic Signal Cycle : {cycle}")
    print("=" * 45)

    print("\nState 1")
    print("Road-A Signal : GREEN")
    print("Road-B Signal : RED")
    print("Status        : Vehicles on Road-A can move.")

    print("\nState 2")
    print("Road-A Signal : YELLOW")
    print("Road-B Signal : RED")
    print("Status        : Road-A should prepare to stop.")

    print("\nState 3")
    print("Road-A Signal : RED")
    print("Road-B Signal : GREEN")
    print("Status        : Vehicles on Road-B can move.")

    print("\nState 4")
    print("Road-A Signal : RED")
    print("Road-B Signal : YELLOW")
    print("Status        : Road-B should prepare to stop.")

    print("\nCycle Completed.")

    cycle += 1