# -*- coding: utf-8 -*-
"""Variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZNWkSRc95TJVLpk9Lpji3to6W0ZHQBJ
"""

# Example 01: Basic Electrical Parameters
# Note:The nominal supply voltage in Bangladesh is 230 V.
# However, the actual voltage is often around 220 V in many areas.

# Electrical Parameters

voltage = 220
current = 5
resistance = 44

# Ohm's Law
calculated_voltage = current * resistance

# Electrical Power
power = voltage * current

print(f"Supply Voltage   : {voltage} V")
print(f"Current       : {current} A")
print(f"Resistance  : {resistance} Ohm")
print(f"Calculated Voltage  : {calculated_voltage} V")
print(f"Power   : {power} W")

# Example_02: Store the Nameplate Data of a Three-Phase Induction Motor
# ==========================================

print("Three-Phase Induction Motor")

# Basic motor information collected from the nameplate

motor_type = "Three-Phase Induction Motor"
application = "Conveyor Belt Drive"

rated_power = 5.5          # kW
rated_voltage = 400        # V
rated_current = 10.8       # A
rated_speed = 1450         # RPM
frequency = 50             # Hz
power_factor = 0.86
efficiency = 91            # %

# Convert rated power into watts
output_power = rated_power * 1000

# Estimate the input power
input_power = output_power / (efficiency / 100)

# Estimate the rated torque
rated_torque = (9550 * rated_power) / rated_speed

print("\nMotor Information")
print("----------------------------")
print("Motor Type :", motor_type)
print("Application :", application)
print("Rated Power :", rated_power, "kW")
print("Rated Voltage :", rated_voltage, "V")
print("Rated Current :", rated_current, "A")
print("Rated Speed :", rated_speed, "RPM")
print("Frequency :", frequency, "Hz")
print("Power Factor :", power_factor)
print("Efficiency :", efficiency, "%")

print("\nEstimated Results")
print("----------------------------")
print("Output Power :", output_power, "W")
print("Estimated Input Power :", round(input_power, 2), "W")
print("Estimated Rated Torque :", round(rated_torque, 2), "N.m")

print("\nThe stored values will be used in the next lab to calculate motor performance.")

# Example 03: Calculate Motor Slip Using Input
# ==========================================

print("Motor Slip Calculator")

synchronous_speed = float(input("Enter synchronous speed (RPM): "))
rotor_speed = float(input("Enter rotor speed (RPM): "))

slip = ((synchronous_speed - rotor_speed) / synchronous_speed) * 100

print("\nCalculation Result")
print("-------------------------")
print(f"Synchronous Speed : {synchronous_speed} RPM")
print(f"Rotor Speed   : {rotor_speed} RPM")
print(f"Motor Slip   : {slip:.2f} %")